# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deblur_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Way1 = QtWidgets.QPushButton(self.centralwidget)
        self.Way1.setGeometry(QtCore.QRect(200, 140, 81, 41))
        self.Way1.setObjectName("Way1")
        self.Way2 = QtWidgets.QPushButton(self.centralwidget)
        self.Way2.setGeometry(QtCore.QRect(300, 140, 81, 41))
        self.Way2.setObjectName("Way2")
        self.Way3 = QtWidgets.QPushButton(self.centralwidget)
        self.Way3.setGeometry(QtCore.QRect(400, 140, 81, 41))
        self.Way3.setObjectName("Way3")
        self.Way5 = QtWidgets.QPushButton(self.centralwidget)
        self.Way5.setGeometry(QtCore.QRect(600, 140, 81, 41))
        self.Way5.setObjectName("Way5")
        self.Way4 = QtWidgets.QPushButton(self.centralwidget)
        self.Way4.setGeometry(QtCore.QRect(500, 140, 81, 41))
        self.Way4.setObjectName("Way4")
        self.blurimg = QtWidgets.QLabel(self.centralwidget)
        self.blurimg.setGeometry(QtCore.QRect(50, 210, 61, 21))
        self.blurimg.setObjectName("blurimg")
        self.sharpimg = QtWidgets.QLabel(self.centralwidget)
        self.sharpimg.setGeometry(QtCore.QRect(520, 210, 51, 21))
        self.sharpimg.setObjectName("sharpimg")
        self.selectPicture = QtWidgets.QPushButton(self.centralwidget)
        self.selectPicture.setGeometry(QtCore.QRect(50, 50, 101, 41))
        self.selectPicture.setObjectName("selectPicture")
        self.blurlabel = QtWidgets.QLabel(self.centralwidget)
        self.blurlabel.setGeometry(QtCore.QRect(30, 240, 421, 271))
        self.blurlabel.setText("")
        self.blurlabel.setObjectName("blurlabel")
        self.sharplabel = QtWidgets.QLabel(self.centralwidget)
        self.sharplabel.setGeometry(QtCore.QRect(490, 240, 421, 271))
        self.sharplabel.setText("")
        self.sharplabel.setObjectName("sharplabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Way1.setText(_translate("MainWindow", "方法一"))
        self.Way2.setText(_translate("MainWindow", "方法二"))
        self.Way3.setText(_translate("MainWindow", "方法三"))
        self.Way5.setText(_translate("MainWindow", "方法五"))
        self.Way4.setText(_translate("MainWindow", "方法四"))
        self.blurimg.setText(_translate("MainWindow", "模糊图片"))
        self.sharpimg.setText(_translate("MainWindow", "复原图片"))
        self.selectPicture.setText(_translate("MainWindow", "请选择图片"))
